name: portofolio
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  bordered_text: ^2.0.0
  cupertino_icons: ^1.0.2
  dismissible_page: ^1.0.1
  flutter:
    sdk: flutter
  flutter_staggered_animations: ^1.1.1
  get: ^4.7.2
  google_fonts: ^6.3.0
  http: ^1.4.0
  localstorage: ^6.0.0
  lottie: ^3.3.1
  oauth1: ^2.0.0
  oauth2: ^2.0.1
  pie_chart: ^5.3.2
  scroll_to_index: ^3.0.1
  translator: ^1.0.3+1
  url_launcher: ^6.1.9
  url_strategy: ^0.3.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/foto/
    - assets/icon/
    - assets/portofolio/avatar/
    - assets/portofolio/bayu/
    - assets/portofolio/crofflite/
    - assets/portofolio/mecrypt/
    - assets/portofolio/wikenyus/
    - assets/portofolio/gezunt/
    - assets/portofolio/nirdesa/
    - assets/portofolio/thrilogic/
    - assets/portofolio/poendoeng/
    - assets/logo/
    - assets/sertif/
    - assets/button/
